### PR TITLE
Introduction and tasks checklist updated 

### PR DESCRIPTION
**Pull request by fieryfalcon**
- Sticking to the advice given in the contributor-guide.md to get well versed in wagtail's community.

### CODE REVIEW

**Comment by KingNonso** [comment]
Superb! Looks good to me... Love the name *fieryfalcon*

**Comment by fieryfalcon** [comment]
Hey Im a beginner to open-source ... Can someone please tell me the reason for my PR not being merged...!

**Review by thibaudcolas — APPROVED** [review]
Looking good @fieryfalcon :)

**Comment by fieryfalcon** [comment]
@thibaudcolas ... Thanks, buddy! 
One more doubt ... can I contribute to wagtail outside the GSoC program as I have aspirations to work on open-source projects

**Comment by fieryfalcon** [comment]
> Superb! Looks good to me... Love the name _fieryfalcon_

Thanks, @KingNonso ... Thought a lot before keeping it as my username...!

**Comment by laymonage** [comment]
> @thibaudcolas ... Thanks, buddy!
> One more doubt ... can I contribute to wagtail outside the GSoC program as I have aspirations to work on open-source projects

Of course, you are more than welcome to do so!

**Pull request merged**
