### PR TITLE
add personal readme

### PR DESCRIPTION
**Pull request by Priscilla-B**

### CODE REVIEW

**Comment by Eltonomwega** [comment]
Great work! @Priscilla-B 🎉
You can also optional add a short description for this PR.
Let me know if you need any help editing this :)

**Review by thibaudcolas — APPROVED** [review]
Nice one @Priscilla-B! No need for you to go through the Django tutorial if you already use Django for work, but it’ll be really helpful for you to go through the Wagtail one.

**Comment by Priscilla-B** [comment]
> Great work! @Priscilla-B 🎉 You can also optionally add a short description for this PR. Let me know if you need any help editing this :)

Thank you !

**Comment by Priscilla-B** [comment]
> Nice one @Priscilla-B! No need for you to go through the Django tutorial if you already use Django for work, but it’ll be really helpful for you to go through the Wagtail one.

Thanks you ! I will do that

**Pull request merged**
